### ISSUE TITLE
acme/autocert: no viable challenge type found

### ISSUE THREAD

**Issue by tiaga** [SenseUnit/dumbproxy#130]
Hello,

The `autocert` option doesn't work for some reason:
```
MAIN    : 2025/05/14 04:06:07 main.go:505: INFO     Starting proxy server...
MAIN    : 2025/05/14 04:06:07 main.go:627: INFO     Proxy server started.
HTTPSRV : 2025/05/14 04:06:17 server.go:3638: http: TLS handshake error from MY_IP:45482: acme/autocert: unable to satisfy "https://acme-v02.api.letsencrypt.org/acme/authz/2397627617/..." for domain "subdomain.example.com": no viable challenge type found
HTTPSRV : 2025/05/14 04:06:17 server.go:3638: http: TLS handshake error from MY_IP:34550: acme/autocert: missing certificate
```

Here is my `docker-compose.yml` file:
```
services:
  dumbproxy:
    image: ghcr.io/senseunit/dumbproxy:1.27.0
    container_name: dumbproxy
    ports:
      - 0.0.0.0:8080:80
      - 0.0.0.0:8443:8443
    entrypoint: /dumbproxy
    command: -bind-address :8443 -auth static://?username=proxy\&password=${PASSWORD} -verbosity 10 -autocert
    restart: always
    security_opt:
      - no-new-privileges=true
```

Tried two domains (that are resolved to the server IP address) but the error is the same. Any ideas why?
